"""Migracao inicial

Revision ID: 9d7b5cef3b3c
Revises: 
Create Date: 2025-11-30 16:40:12.476555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7b5cef3b3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('whatsapp', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pessoas_Fisicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pessoas_Juridicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=False),
    sa.Column('nome_replegal', sa.String(), nullable=False),
    sa.Column('cpf_replegal', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pessoas_Juridicas')
    op.drop_table('Pessoas_Fisicas')
    op.drop_table('Pessoas')
    # ### end Alembic commands ###
